format = """
$directory $git_branch$git_status $rust $python $golang $php $nodejs $ruby $java $c $dotnet $perl $lua $haskell $elixir $docker_context $kubernetes $terraform $aws 
$character
"""

right_format = """
[ h3llo fr13nd! ](bold green)
"""

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[$path]($style)"

[git_branch]
symbol = "î‚  "
style = "bold green"
format = "[$symbol$branch]($style)"

[git_status]
style = "green"
format = "[$all_status$ahead_behind]($style)"

[rust]
symbol = "ğŸ¦€ "
style = "bold green"
format = "[$symbol$version]($style)"

[python]
symbol = "ğŸ"
style = "bold green"
format = "[$symbol$version](bold green) [(venv: $virtualenv)](bold red)"


[golang]
symbol = "ğŸ¹ "
style = "bold green"
format = "[$symbol$version]($style)"

[php]
symbol = "ğŸ˜ "
style = "bold green"
format = "[$symbol$version]($style)"


[nodejs]
symbol = "îœ˜ "
style = "bold green"
format = "[$symbol$version]($style)"

[ruby]
symbol = "ğŸ’ "
style = "bold green"
format = "[$symbol$version]($style)"

[java]
symbol = "â˜• "
style = "bold green"
format = "[$symbol$version]($style)"

[c]
symbol = "î˜ "
style = "bold green"
format = "[$symbol$version]($style)"

[dotnet]
symbol = "î¿ "
style = "bold green"
format = "[$symbol$version]($style)"

[perl]
symbol = "ğŸª "
style = "bold green"
format = "[$symbol$version]($style)"

[lua]
symbol = "ğŸŒ™ "
style = "bold green"
format = "[$symbol$version]($style)"

[haskell]
symbol = "Î» "
style = "bold green"
format = "[$symbol$version]($style)"

[elixir]
symbol = "ğŸ’§ "
style = "bold green"
format = "[$symbol$version]($style)"

[docker_context]
symbol = "ğŸ³ "
style = "bold green"
format = "[$symbol$context]($style)"

[kubernetes]
symbol = "â˜¸ï¸ "
style = "bold green"
format = "[$symbol$context]($style)"

[terraform]
symbol = "ğŸ’  "
style = "bold green"
format = "[$symbol$workspace]($style)"

[aws]
symbol = "ğŸ…°ï¸ "
style = "bold green"
format = "[$symbol$profile]($style)"

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"
vimcmd_symbol = "[â¯](bold green)"

